# Generated by Django 4.2.1 on 2023-05-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='account',
            new_name='customuser',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
