# Generated by Django 4.2.1 on 2023-05-29 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vts', '0002_rename_account_interaction_customuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='gender',
            new_name='gender_id',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='organization',
            new_name='organization_id',
        ),
        migrations.RemoveField(
            model_name='bracelet',
            name='unique_identifier',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='bracelet',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vts.organization'),
        ),
        migrations.AddField(
            model_name='service',
            name='allowed_roles',
            field=models.ManyToManyField(related_name='allowed_roles', to='vts.role'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
