# Generated by Django 4.2.1 on 2023-05-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vts', '0004_alter_service_description_alter_service_minimum_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='organization_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vts.organization'),
        ),
    ]
