# Generated by Django 4.2.1 on 2023-06-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vts', '0006_rename_organization_id_bracelet_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bracelet',
            old_name='user',
            new_name='customuser',
        ),
    ]
