# Generated by Django 4.2.1 on 2023-06-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts', '0007_rename_user_bracelet_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='info',
            field=models.CharField(null=True),
        ),
    ]
