# Generated by Django 4.2.1 on 2023-06-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts', '0008_interaction_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='rfid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
